### ISSUE TITLE
ModuleNotFoundError: No module named 'convlab.dst.sumbt.multiwoz' [BUG] 

### ISSUE THREAD

**Issue by ranchlai** [ConvLab/ConvLab-3#114]
Code missing for sumbt. How to fix?

There are many scripts that rely on sumbt, e.g., ```python test_SUMBT-LaRL.py```.

**Comment by zqwerty** [comment]
@carelvniekerk Could you have a look?

**Comment by carelvniekerk** [comment]
I am currently having a look at this will post a fix soon.

**Comment by carelvniekerk** [comment]
@ranchlai I have updated the example script test_SUMBT-LaRL.py. The SUMBT model will now import. Just as a note. Since SetSUMBT is an extension of SUMBT, we now import SetSUMBT and the model is configured as a SUMBT model. I am training a checkpoint which I will upload, but you could also train it using the sumbt_multiwoz21 config for SetSUMBT.

Unfortunately the LaRL policy is not currently maintained in Convlab version 3, which means this policy does not support the new format of the dialogue state. Please see the paper for policies currently maintained. You could for example use the LAVA policy instead of LaRL.
