### ISSUE TITLE
[Feature] Deploy folder(Interactive Tool) update

### ISSUE THREAD

**Issue by dengbuqi** [ConvLab/ConvLab-3#147]
**Describe the feature**
Will you update the deploy folder? I want to try interactive tools.

**Expected behavior**
Convlan-2 has a perfect Interactive Tool demo, Is it possible to update to Convlab-3?

**Additional context**
I  try to run the [deploy demo](https://github.com/ConvLab/ConvLab-3/tree/master/convlab/deploy) in ConvLab-3,  but I failed!

**Comment by zqwerty** [comment]
Sorry, I will try to fix it.

**Comment by dengbuqi** [comment]
> Sorry, I will try to fix it.

Many thanks for the prompt reply. 
Your team has done an excellent job on an open-source dialog system platform. 
I think you can recruit some community members to maintain the details while your team can focus on research.
Thanks again!

**Comment by zqwerty** [comment]
Thank you! I have pushed a fix that updates the example dep config

**Comment by zqwerty** [comment]
Basically, the deploy tool itself keeps unchanged, since we do not change the module interface of ConvLab-2. However, the policy module changes a lot, so we need to check the initialization of policy models to ensure they can be loaded directly (without constructing and passing a vectorizer).
@ChrisGeishauser could you have a look at my modification on `vtrace.py`?
https://github.com/ConvLab/ConvLab-3/pull/148/files#diff-78c93e8b3ee1506d6de5d46ab0772f479d62c1547462995058d566ab7243ab61

**Comment by zqwerty** [comment]
Thank @ChrisGeishauser update policy model interfaces in #149. Now I think all policy model can be used in the deploy tool

**Comment by dengbuqi** [comment]
@zqwerty Highly appreciated! Thanks a lot!
