### ISSUE TITLE
test_end2end VS.  convlab/policy/evaluate.py

### ISSUE THREAD

**Issue by AtheerAlgherairy** [ConvLab/ConvLab-3#178]
I have a question regarding evaluation in ConvLab-3, if possible.

What is the difference between the following two scenarios:

-  **test_end2end**(e.g. examples/agent_examples) 
-   **convlab/policy/evaluate.py** 

**In my evaluations using both evaluate.py and test_end2end(), I observed the followings:**

1. Varied results in the average turns.
2. Comparable results for complete/success rate.
3. I'm curious about the definition of "average actions" - does it refer to the length of the system response - since I’m working at natural language level?

![Screen Shot 1445-05-18 at 10 29 43 PM](https://github.com/ConvLab/ConvLab-3/assets/7421065/8b3580c5-6c43-4b57-bda9-fabd7e15a2e2)

I ensured consistency by using the same "model_path" for the PPO policy on the system side and maintaining identical configurations for all components, including BERT NLU, RuleDST, and template NLG. 

I have attached the two configuration JSON files (that I used for evaluate.py): 

[ABUS_policy_ABUS.json](https://github.com/ConvLab/ConvLab-3/files/13544755/ABUS_policy_ABUS.json)
[ABUS_policy_GenTUS.json](https://github.com/ConvLab/ConvLab-3/files/13544756/ABUS_policy_GenTUS.json)

Your assistance in clarifying these observations would be greatly appreciated.

**Comment by hsien1993** [comment]
Hi @AtheerAlgherairy,
1. Difference in average turns: a system response and a user response is one turn in `convlab.policy.evaluate`(https://github.com/ConvLab/ConvLab-3/blob/f46509fb5ddee34fb3e6ffda0281c5ff9605c925/convlab/policy/evaluate.py#L121), but two turns in `convlab.util.analysis_tool.analyzer`(https://github.com/ConvLab/ConvLab-3/blob/f46509fb5ddee34fb3e6ffda0281c5ff9605c925/convlab/util/analysis_tool/analyzer.py#L134). Therefore, if you divide the results in test_end2end() by 2, then you can find out the results are comparable. You can choose the setting which you would like to use :)
2. Yes. The average number of actions is the length of semantic actions. Since you are working on the natural language level, it will be the average length of strings.
